input {
  http {
    port => 5044
    codec => json
  }
}
filter {
  # HTTP Input Plugin은 Request Path를 [headers][request_path]에 저장합니다. (예: "/system_logs")
  if [headers][request_path] {
    mutate {
      add_field => { "[@metadata][target_index]" => "%{[headers][request_path]}" }
    }
    mutate {
      gsub => [ "[@metadata][target_index]", "^/", "" ]
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "default_logs" }
    }
  }
  # Elasticsearch 인덱싱 시 데이터 용량을 줄이기 위해 헤더 정보 및 불필요한 메타데이터 필드 삭제
  mutate {
    remove_field => [ "headers", "host", "@version" ]
  }
}
output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_URL}"]
    index => "%{[@metadata][target_index]}"
  }
  
  # 원격 디버깅/로그 모니터링을 위해 stdout 출력
  stdout {
    codec => rubydebug
  }
}
