name: Deploy POOM-ELK
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy files to ELK server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ELK_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose-elk.yml,config/"
          target: "/opt/elk"
      - name: Deploy to ELK server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ELK_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /opt/elk
            docker compose -f docker-compose-elk.yml --env-file .env pull
            docker compose -f docker-compose-elk.yml --env-file .env up -d
